gestao/urls.py
from django.urls import path

from . import views

app_name = 'gestao'

urlpatterns = [
    path('', views.index, name='index'),
    # path('cadastrar/', views.cadastrar, name='cadastrar'),
    # path('salvar/', views.save, name='save'),
    path('salvar/', views.CadastrarView.as_view(), name='save'),
    # path('listar/', views.listar, name='listar'),
    path('listar/', views.ListarView.as_view(), name='listar'),
    # path('livro/<int:livro_id>', views.view, name='view'),
    path('livro/<int:pk>', views.DetailView.as_view(), name='view'),
    path('teste/', views.teste, name='teste'),
]

livraria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('gestao/', include('gestao.urls')),
    path('admin/', admin.site.urls),
]

gestao/models.py
from django.db import models

# Create your models here.
class Livro(models.Model):
    titulo = models.CharField(max_length=256)
    paginas = models.IntegerField()

gestao/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect, render
from django.urls import reverse_lazy
from django.views import generic
from .models import Livro

def index(request):
    return render(request, 'gestao/pagina.html')

class CadastrarView(generic.CreateView):
    model = Livro
    template_name = 'gestao/form.html'
    success_url = reverse_lazy('gestao:index')
    fields = ['titulo', 'paginas']

# def cadastrar(request):
#     return render(request, 'gestao/form.html')

# def save(request):
#     titulo = request.POST.get('titulo')
#     paginas = int(request.POST.get('paginas'))
#     livro = Livro(titulo=titulo, paginas=paginas)
#     livro.save()
#     return HttpResponseRedirect(reverse('gestao:index'))

class ListarView(generic.ListView):
    template_name = 'gestao/list.html'
    context_object_name = 'livros'

    def get_queryset(self):
        return Livro.objects.all()

# def listar(request):
#     livros = Livro.objects.all()
#     return render(request, 'gestao/list.html', {'livros': livros})


class DetailView(generic.DetailView):
    model = Livro
    template_name = 'gestao/view.html'


# def view(request, livro_id):
#     # livro = Livro.objects.get(id=livro_id)
#     livro = get_object_or_404(Livro, pk=livro_id)
#     return render(request, 'gestao/view.html', { 'livro': livro })

def teste(request):
    return render(request, 'gestao/base_gestao.html')

gestao/templates/gestao/base_gestao.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'list.css' %}" />
{% endblock static %}

{% block content %}
<h2>Base Gestão</h2>
{% endblock content %}

gestao/templates/gestao/form.html
{% extends 'gestao/base_gestao.html' %}

{% block content %}
<form action="{% url 'gestao:save' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1> Cadastro de Livros</h1>
        </legend>
        <label for="titulo">Título do livro</label>
        <br/>
        <input type="text" name="titulo" id="titulo" value="">
        <br/>
        <br/>
        <label for="paginas">Páginas</label>
        <br/>
        <input type="text" name="paginas" id="paginas" value="">
        <br/>
        <br/>
        <input type="submit" value="Salvar">
    </fieldset>
</form>
{% endblock content %}

gestao/templates/gestao/list.html
{% extends 'gestao/base_gestao.html' %}

{% block content %}
    {% if livros %}
    <ul>
        {% for livro in livros %}
        <li>
            <a href="{% url 'gestao:view' pk=livro.id %}">
                {{ livro.titulo}}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Nenhum livro cadastrado</p>
    {% endif %}
{% endblock content %}

gestao/templates/gestao/pagina.html
<h1>Bem-vindo à Livraria!</h1>
<br/>
<a href="{% url 'gestao:listar' %}">Listar todos os livros</a>
<br/>
<a href="{% url 'gestao:save' %}">Cadastrar livro</a>

gestao/templates/gestao/view.html
{% extends 'gestao/base_gestao.html' %}

{% block content %}
    <p>Título: {{ livro.titulo }}</p>
    <p>Páginas: {{ livro.paginas }}</p>
{% endblock content %}

templates/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'base.css' %}" />

{% block static %}
{% endblock static %}

<h1>Gestão de Livros</h1>
{% block content %}
{% endblock content %}